### ISSUE TITLE
Inter-Board Connection for Messaging Spike

### ISSUE THREAD

**Issue by MichaelLally** [gcivil-nyu-org/spring2020-cs-gy-9223-hardware#22]
**User story**
As developer, I want to decided on a physical messaging platform so that on-vehicle Raspberry Pi's can communicate via a hardwire.

Research needs to get done into what type of cable will be used to connect on-vehicle boards/RPi's so that messaging can be done via a hardwire. This could be an ethernet cable, a CAN cable, or a more custom setup.

This spike includes determining how the cable with interface with raspberry pi boards.

**Acceptance criteria**
The connection system must be capable of connecting multiple (more than 2) Raspberry Pi's and allow for messages to be passed between them.

**Definition of Done**
A connection system has been decided on, sourced from a supplier, and the details have been entered into the part's procurement sheet.

**Comment by ab7289** [comment]
Initial hardware options:

USB
Ethernet
- seems to be the most often suggested

GPIO?

**Comment by ab7289** [comment]
notes: https://docs.google.com/document/d/1qYPzAU-9pJQbozs4V5Zcva_tOlrtiE3-9WlJxyE4cDY/edit#

**Comment by ab7289** [comment]
From research, the best option appears to be Ethernet all around.
