### ISSUE TITLE
Messaging Protocol for Inter-Board Connections Spike

### ISSUE THREAD

**Issue by MichaelLally** [gcivil-nyu-org/spring2020-cs-gy-9223-hardware#24]
**User story**
As developer, I want to decide on a messaging protocol or standard so that firmware can be written for encoding and decoding to this standard.

This protocol is to be used for **on-vehicle communications** between boards via the hardwire or bus. Possible candidates are CAN, JSON, or any other format that can easily be transmitted over a wire.

**Acceptance criteria**
A messaging standard has been decided on that is compatible with our hardware.

**Definition of Done**
The messaging standard has been recorded/documented.

**Comment by ab7289** [comment]
The teams have decided on using JSON.
